f = open("pg.txt", encoding="UTF-8")
lause = f.read().replace(" aga", ", aga")
lause1 = lause.replace(" sest", ", sest")
lause2 = lause1.replace(" et", ", et")
lause3 = lause2.replace(" kuid", ", kuid")
lause4 = lause3.replace(" vaid", ", vaid")
lause5 = lause4.replace(" siis", ", siis")
print(lause5)
f.close()